INCS += $(INCLUDE)/no_os_rtc.h

INCS += $(PLATFORM_DRIVERS)/$(PLATFORM)_i2c.h		\

SRCS += $(PLATFORM_DRIVERS)/$(PLATFORM)_delay.c	\
	$(PLATFORM_DRIVERS)/$(PLATFORM)_i2c.c

INCS += $(PLATFORM_DRIVERS)/$(PLATFORM)_timer.h			\
	$(PLATFORM_DRIVERS)/$(PLATFORM)_gpio.h

SRCS += $(PLATFORM_DRIVERS)/$(PLATFORM)_delay.c	\
	$(PLATFORM_DRIVERS)/$(PLATFORM)_timer.c		\
	$(PLATFORM_DRIVERS)/$(PLATFORM)_gpio.c	
