INCS += $(PLATFORM_DRIVERS)/$(PLATFORM)_timer.h			\
	$(PLATFORM_DRIVERS)/$(PLATFORM)_uart.h

SRCS += $(PLATFORM_DRIVERS)/$(PLATFORM)_delay.c	\
	$(PLATFORM_DRIVERS)/$(PLATFORM)_timer.c		\
	$(PLATFORM_DRIVERS)/$(PLATFORM)_uart.c
