# Choose example you want to run (only 1 allowed per build)
TX_EXAMPLE = n
RX_EXAMPLE = n
LOOPBACK_EXAMPLE = y

include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk
